package.xml
setup.cfg
setup.py

#5 Add ROS-necessities

---

.github/workflows/release.yml
Dockerfile

change dockerfile and release.yml

---

.github/workflows/test.yml

"#18 add necst-msgs"

---

.github/workflows/gh-pages.yml
tests/conftest.py
tests/test_nothing.py

**Checks**
This PR closes #24.

Fix workflow trigger

---

necst/ctrl/antenna_simulater.py

**Checks**
This PR closes #26.

Implement antenna motion simulator

---

.devcontainer/Dockerfile
necst/__init__.py
necst/core/__init__.py
necst/core/commander.py
necst/core/exec_record.py
necst/core/recorder.py
necst/ctrl/antenna/__init__.py
necst/ctrl/antenna/coordinate_conversion.py
necst/ctrl/antenna/driver.py
necst/ctrl/antenna/encoder.py
necst/ctrl/antenna/horizontal_coord.py
necst/ctrl/antenna/motor.py
necst/ctrl/antenna/pid_controller.py
necst/ctrl/antenna/sim_devices.py
necst/ctrl/exec_antenna_cal.py
necst/ctrl/exec_antenna_dev.py
necst/ctrl/exec_antenna_sim.py
package.xml
setup.py
tests/core/test_commander.py
tests/ctrl/test_antenna_controller.py
tests/ctrl/test_coordinate_conversion.py
tests/integration/test_antenna.py

**Checks**
This PR closes #33.

Track the target

---

package.xml
setup.py

**Checks**
This PR closes #37.

Update project version

---

Dockerfile

**Checks**
This PR closes #39.

Fix environment to run NECST

---

package.xml
setup.py

Version 0.2.2

---

necst/ctrl/antenna/motor.py

Resolve bugs identified during in-situ testing

---

necst/ctrl/antenna/motor.py

**Checks**
This PR closes #45.
See also: https://github.com/necst-telescope/neclib/issues/150

Support real-time control of motor controller

---

Dockerfile

**Checks**
This PR closes #46.

Add installation of pciutils

---

.devcontainer/Dockerfile
.github/workflows/test.yml
README.md
tests/docs/test_build.py
tests/integration/test_antenna.py

**Checks**
This PR closes #51.

Add code coverage report

---

.github/workflows/test.yml

Fix command to dump coverage report

---

.devcontainer/Dockerfile
necst/core/recorder.py
tests/core/test_recorder.py

**Checks**
This PR closes #50.

#50 recorder

---

docs/conf.py
necst/core/authorizer.py
necst/core/commander.py
necst/core/privileged_node.py
necst/ctrl/antenna/horizontal_coord.py
tests/core/test_commander.py
tests/ctrl/test_coordinate_conversion.py
tests/docs/test_build.py
tests/integration/test_antenna.py

**Checks**
This PR closes #56.

Use privilege handler in commander

---

necst/ctrl/antenna/sim_devices.py
tests/ctrl/test_sim_devices.py

**Checks**
This PR closes #59.

add test_sim_devices.py

---

necst/core/recorder.py
necst/ctrl/antenna/horizontal_coord.py
tests/core/test_recorder.py

change DBWriter to Recorder

---

necst/ctrl/antenna/__init__.py
necst/ctrl/antenna/thermometer_reader.py

**Checks**
This PR closes #63 
Thermometer()はまだ作っていませんが、temp、hum、pressを与える関数になる予定です。これらの値はself.thermo.read()で読めるようにする予定です。

add thermometer_reader

---

necst/ctrl/antenna/pid_controller.py

**Checks**
This PR closes #68.

Use config values for PID controller

---

necst/ctrl/antenna/encoder.py
necst/ctrl/antenna/motor.py

**Checks**
This PR closes #69.

Reflect change of device controller naming convention

---

necst/ctrl/exec_antenna_dev.py

**Checks**
This PR closes #73.

add ThermometerReader in exec_antenna_dev

---

necst/ctrl/antenna/pid_controller.py

**Checks**
This PR closes #60.

Use deceleration calculator

---

necst/ctrl/antenna/thermometer_reader.py

**Checks**
This PR closes #80.

Fix function usage

---

necst/ctrl/antenna/pid_controller.py
necst/ctrl/exec_antenna_dev.py

**Checks**
This PR closes #82.

Fix dropped command handling

---

necst/core/__init__.py
necst/core/device_node.py
necst/ctrl/antenna/encoder.py
necst/ctrl/antenna/motor.py
necst/ctrl/antenna/thermometer_reader.py

Reflect quick fixes done in trip

---

necst/core/authorizer.py
necst/core/privileged_node.py
tests/core/test_authority.py

**Checks**
This PR closes #87.

Avoid deadlock after ping attempt

---

docs/index.md
necst/ctrl/antenna/pid_controller.py

**Checks**
This PR closes #90.

Use context manager to change PID configurations

---

necst/__init__.py
necst/core/recorder.py
tests/test_qos.py

**Checks**
This PR closes #92.

Add QoS policy detector

---

necst/ctrl/antenna/horizontal_coord.py

#84 add weather status change

---

necst/ctrl/antenna/horizontal_coord.py
necst/ctrl/antenna/thermometer_reader.py

#93-change namespace from antenna to ctrl

---

.github/ISSUE_TEMPLATE/release.md
package.xml
setup.py

**Checks**
This PR closes #98.

Release v0.3.1

---

.github/workflows/test.yml
necst/__init__.py
necst/core/alert/antenna_drive_range.py
necst/core/alert/antenna_speed.py
necst/core/auth/authorizer.py
necst/core/auth/privileged_node.py
necst/core/commander.py
necst/core/device_node.py
necst/core/recorder.py
necst/ctrl/antenna/encoder.py
necst/ctrl/antenna/horizontal_coord.py
necst/ctrl/antenna/motor.py
necst/ctrl/antenna/pid_controller.py
necst/ctrl/antenna/sim_devices.py
necst/ctrl/antenna/thermometer_reader.py
necst/definitions.py
necst/utils/ros_interface.py
tests/conftest.py
tests/core/test_authority.py
tests/core/test_commander.py

**Checks**
This PR closes #101.

Define topic and service configurations

---

.devcontainer/devcontainer.json
Dockerfile
necst/core/auth/authorizer.py
necst/core/auth/privileged_node.py
necst/core/commander.py
necst/core/server_node.py
necst/ctrl/calibrator/chopper.py
necst/definitions.py
necst/utils/ros_thread.py
tests/conftest.py
tests/core/test_authority.py
tests/core/test_commander.py

**Checks**
This PR closes #72.

Add chopper controller

---

.devcontainer/Dockerfile
Dockerfile

**Checks**
This PR closes #117.

Change RMW implementation in devcontainer

---

package.xml
setup.py

**Checks**
This PR closes #119.

Release v0.3.2

---

necst/ctrl/antenna/motor.py

**Checks**
This PR closes #115.

Convert quantity data to float

---

necst/ctrl/antenna/pid_controller.py
necst/definitions.py
tests/core/test_commander.py

**Checks**
This PR closes #121.

Fix real-time command selection

---

necst/core/commander.py

**Checks**
This PR closes #127

#127 Fix typo and enable to use `"scan"` command

---

necst/core/alert/alert_handler_node.py
necst/core/commander.py
necst/definitions.py
tests/core/test_commander.py

**Checks**
This PR closes #130.

Fix convergence check timing

---

necst/core/recorder.py

**Checks**
This PR closes #123

#123 Fix msg string length if specified

---

necst/ctrl/antenna/horizontal_coord.py
tests/ctrl/test_coordinate_conversion.py

**Checks**
This PR closes #128.

Fix procedure on communication loss with encoder

---

necst/core/recorder.py

**Checks**
This PR closes #138.

Fix data type parsing

---

necst/core/commander.py
necst/core/recorder.py
necst/ctrl/antenna/horizontal_coord.py
necst/ctrl/antenna/pid_controller.py
necst/definitions.py

**Checks**
This PR closes #129.

Fix controller setting

---

Dockerfile
README.md
necst/__init__.py
necst/core/commander.py
necst/core/recorder.py
necst/ctrl/antenna/horizontal_coord.py
necst/ctrl/antenna/motor.py
necst/ctrl/antenna/pid_controller.py
necst/definitions.py
necst/rx/spectrometer.py
tests/ctrl/test_antenna_controller.py

**Checks**
This PR closes #143.

Support generator type coordinate calculation result

---

necst/core/commander.py

**Checks**
This PR closes #148.

Fix missing return statement

---

necst/rx/spectrometer.py

**Checks**
This PR closes #151.

Add ability to drop spectral data

---

Dockerfile
bin/necst
bin/otf.py
bin/radio_pointing.py
necst/__init__.py
necst/core/auth/authorizer.py
necst/core/auth/privileged_node.py
necst/core/commander.py
necst/ctrl/antenna/horizontal_coord.py
necst/ctrl/antenna/tracking_status.py
necst/definitions.py
necst/executors/auth.py
necst/procedures/observations/observation_base.py
necst/procedures/observations/otf.py
necst/procedures/observations/radio_pointing.py
necst/procedures/observations/rsky.py
necst/procedures/observations/skydip.py
necst/rx/spectrometer.py
package.xml
setup.py
tests/conftest.py
tests/core/test_authority.py
tests/core/test_commander.py
tests/ctrl/test_coordinate_conversion.py
tests/procedures/test_rsky.py
tests/procedures/test_skydip.py

**Checks**
This PR closes #152.

Add OTF observation script

---

necst/core/auth/privileged_node.py
necst/core/commander.py
package.xml
setup.py
tests/ctrl/test_coordinate_conversion.py

**Checks**
This PR closes #157.

Add documentation on `Commander` usage

---

necst/core/commander.py
necst/definitions.py
necst/rx/sis_bias.py

**Checks**
This PR closes #159.

Rename SISBias message

---

Dockerfile

**Checks**
This PR closes #169.

Release v0.6.0

---

bin/hot_monitor.py
necst/procedures/observations/__init__.py
necst/procedures/observations/hot_monitor.py

**Checks**
This PR closes #175

#175 hot moni

---

bin/hot_monitor.py
necst/procedures/observations/hot_monitor.py

**Checks**
This PR closes #179

#179 Add new argment: record rate

---

bin/hot_monitor.py
necst/procedures/observations/hot_monitor.py

#186 modify data type and documentation.

---

Dockerfile

**Checks**
This PR closes #188

#188 change neclib version

---

package.xml

**Checks**
This PR closes #190

#190 new change for release

---

package.xml
setup.py

**Checks**
This PR closes #192

#192 change version in setup.py & package.xml

---

necst/executors/chopper_sim.py

**Checks**
This PR closes #194

"#194 executor "

---

necst/executors/antenna_sim.py

**Checks**
This PR closes #196

"#196 antenna sim"

---

necst/rx/hemt_bias.py
necst/rx/sis_bias.py

**Checks**
This PR closes #198

#198 add channel filter

---

necst/rx/attenuator.py

**Checks**
This PR closes #200

#200 change .value

---

package.xml
setup.py

**Checks**
This PR closes #203

release v0.6.4

---

Dockerfile
package.xml
setup.py

**Checks**
This PR closes #205

#205 change neclib version & release0.6.4.1

---

setup.py

#207 Update setup.py

---

package.xml

#207 Update package.xml

---

necst/rx/attenuator.py

**Checks**
This PR closes #210

fixed attenuator

---

necst/ctrl/antenna/pid_controller.py

**Checks**
This PR closes #215

"#215 procceding order"

---

necst/procedures/observations/hot_monitor.py
necst/procedures/observations/observation_base.py

**Checks**
This PR closes #213.

#213 change where send reduce command

---

necst/procedures/observations/observation_base.py

**Checks**
This PR closes #225

#225 fix parameter of config

---

bin/optical_pointing.py
necst/rx/ccd.py

**Checks**
This PR closes #233

#233 edit bin comment

---

bin/optical_pointing.py

**Checks**
This PR closes #236

#236 opt bin

---

Dockerfile
necst/core/commander.py
necst/ctrl/antenna/horizontal_coord.py

**Checks**
This PR closes #226

[WIP] #226 change necst to new version

---

.github/ISSUE_TEMPLATE/release.md
Dockerfile
package.xml
setup.py

**Checks**
This PR closes #232

update version number to v0.7.0

---

necst/procedures/observations/optical_pointing.py

**Checks**
This PR closes #242

#242 fix optical pointing

---

necst/rx/__init__.py

**Checks**
This PR closes #238

#238 fix import of rx

---

bin/optical_pointing.py
necst/core/commander.py
necst/procedures/observations/optical_pointing.py

**Checks**
This PR closes #239

#239 optical data

---

necst/rx/ccd.py

**Checks**
This PR closes #246

#246 fix topic name

---

Dockerfile
necst/rx/ccd.py
package.xml
setup.py

**Checks**
This PR closes #248

#248 fix msg name

---

necst/core/commander.py
necst/definitions.py
necst/rx/ccd.py

**Checks**
This PR closes #250

#250 ccd srv

---

Dockerfile
necst/definitions.py
necst/executors/powermeter.py
necst/rx/__init__.py
necst/rx/powermeter.py

**Checks**
This PR closes #254

[WIP] #254 Add Powermeter.py

---

Dockerfile
necst/core/commander.py
necst/definitions.py
necst/executors/local_attenuator.py
necst/rx/__init__.py
necst/rx/attenuator.py
necst/rx/local_attenuator.py
package.xml
setup.py

**Checks**
This PR closes #256

#256 add local_attenuator.py

---

necst/core/__init__.py
necst/core/com_delay_test.py
necst/core/com_delay_test_topic.py
necst/core/commander.py
necst/definitions.py
necst/executors/com_delay_test.py
necst/executors/com_delay_test_topic.py

add test communication delay

---

Dockerfile
necst/core/commander.py
necst/ctrl/__init__.py
necst/ctrl/membrane/__init__.py
necst/ctrl/membrane/motor.py
necst/definitions.py
necst/executors/memb.py
package.xml
setup.py

**Checks**
This PR closes #264

#264 membrane

---

necst/ctrl/antenna/motor.py
necst/ctrl/membrane/motor.py
necst/executors/memb.py

**Checks**
This PR closes #266

#266 fixed def main of AntennaMotor and MembraneMotor

---

necst/ctrl/dome/encoder.py
necst/ctrl/dome/motor.py
necst/ctrl/membrane/motor.py

**Checks**
This PR closes #269

#269 debug dome

---

necst/ctrl/dome/encoder.py
necst/ctrl/dome/motor.py
necst/definitions.py

#271 domeliimit

---

necst/executors/chopper.py

**Checks**
This PR closes #274

#274 make chopper executor

---

necst/core/commander.py

change config

---

necst/core/commander.py
necst/ctrl/membrane/motor.py

**Checks**
This PR closes #281

#281 memb_ocの待機判定を変えた

---

necst/core/commander.py
necst/ctrl/dome/motor.py
necst/definitions.py

**Checks**
This PR closes #278

#278 add wait oc

---

necst/core/commander.py
necst/ctrl/dome/encoder.py
necst/ctrl/dome/motor.py
necst/definitions.py

debug dome

---

necst/executors/weather_station.py

**Checks**
This PR closes #285

#285 separate

---

.github/actions/setup-necst/action.yml
Dockerfile
necst/core/commander.py
necst/ctrl/__init__.py
necst/ctrl/antenna/motor.py
necst/ctrl/dome/motor.py
necst/ctrl/drive/__init__.py
necst/ctrl/drive/motor.py
necst/ctrl/membrane/motor.py
necst/definitions.py
necst/executors/drive.py
tests/ctrl/test_coordinate_conversion.py

**Checks**
This PR closes #283

#283 drive

---

necst/ctrl/antenna/pid_controller.py
tests/ctrl/test_antenna_controller.py

**Checks**
This PR closes #252

#252 scan param

---

necst/ctrl/__init__.py
necst/ctrl/antenna/pid_controller.py
necst/executors/antenna_dev.py
necst/executors/dome_calc.py
necst/executors/status.py

**Checks**
This PR closes #287

#287 fixpid

---

necst/core/commander.py
necst/ctrl/antenna/encoder.py
necst/ctrl/antenna/pid_controller.py
necst/ctrl/dome/encoder.py

**Checks**
This PR closes #291

#291 fixscan

---

necst/ctrl/dome/__init__.py
necst/ctrl/dome/encoder.py
necst/executors/dome_dev.py

**Checks**
This PR closes #293

"#293-separation"

---

necst/core/commander.py
necst/ctrl/mirror/m2.py

mirror wait

---

necst/core/commander.py

debug mirror

---

necst/ctrl/antenna/pid_controller.py
necst/definitions.py

Reverts necst-telescope/necst#298

Revert "#297 fixscan"

---

bin/sis_iv.py
bin/sis_tuning.py
necst/core/commander.py
necst/procedures/measurement/__init__.py
necst/procedures/measurement/sis_iv.py
necst/procedures/measurement/sis_tuning.py
necst/rx/attenuator.py
necst/rx/hemt_bias.py
necst/rx/local_attenuator.py
necst/rx/signal_generator.py
necst/rx/sis_bias.py
necst/rx/thermometer.py

**Checks**
This PR closes #295

#295 nasco

---

necst/definitions.py
necst/executors/vacuum_gauge.py
necst/rx/__init__.py
necst/rx/vacuum_gauge.py

**Checks**
This PR closes #259

#259 vacuum

---

necst/core/commander.py
necst/procedures/measurement/sis_iv.py
necst/procedures/measurement/sis_tuning.py
necst/rx/local_attenuator.py
necst/rx/sis_bias.py

**Checks**
This PR closes #302

#302 modi sisiv

---

necst/core/commander.py
necst/core/recorder.py
necst/definitions.py

**Checks**
This PR closes #308

#308 change 

---

necst/core/commander.py

debug recorder

---

necst/core/commander.py
necst/procedures/measurement/sis_tuning.py

**Checks**
This PR closes #311

#311 timestamp

---

bin/position_switching.py
necst/procedures/observations/__init__.py
necst/procedures/observations/position_switching.py

**Checks**
This PR closes #313

#313 add psw

---

bin/sis_tuning.py
necst/core/commander.py
necst/procedures/measurement/sis_tuning.py
necst/rx/attenuator.py

**Checks**
This PR closes #318 
- NANTEN2サイトで終わりきらなかったらデバッグを終了させました。
- 主に測定スクリプトの測定時間間隔のデフォルト値の修正、SGのデバッグ、真空計Commanderの追加を行いました。

#318 debug nanten2

---

necst/rx/spectrometer.py

**Checks**
This PR closes #315

#315 ac240

---

.github/workflows/test.yml
necst/procedures/measurement/measurement_base.py
necst/procedures/observation_base.py

**Checks**
This PR closes #320

#320 modi config saving

---

package.xml
setup.py

**Checks**
This PR closes #322

#322 change file

---

.github/workflows/gh-pages.yml
package.xml
setup.py

#322 sphinx

---

necst/procedures/measurement/sis_iv.py
necst/rx/hemt_bias.py
necst/rx/sis_bias.py

**Checks**
This PR closes #330 
- デバイスデバッグは終了しています。詳しくはこのログを確認してください。: https://github.com/necst-telescope/internal/discussions/137

#330 change bias

---

necst/rx/attenuator.py
necst/rx/hemt_bias.py
necst/rx/local_attenuator.py
necst/rx/powermeter.py
necst/rx/signal_generator.py
necst/rx/sis_bias.py
necst/rx/thermometer.py
necst/rx/vacuum_gauge.py

**Checks**
This PR closes #339

#339 retry rx

---

necst/rx/attenuator.py

**Checks**
This PR closes #341

#341 modi config resolving

---

necst/rx/signal_generator.py
necst/rx/sis_bias.py

**Checks**
This PR closes #344.

Fix typos in `necst/rx/`

---

bin/otf.py
bin/radio_pointing.py
necst/core/commander.py
necst/definitions.py
necst/procedures/observation_base.py
necst/rx/spectrometer.py

**Checks**
This PR closes #336

#336 add tp command

---

necst/ctrl/antenna/tracking_status.py
tests/core/test_commander.py

**Checks**
This PR closes #303

#303 fixstatus

---

.github/actions/setup-necst/action.yml
necst/procedures/measurement/sis_tuning.py

**Checks**
This PR closes #349

#349 fix  typo and if

---

package.xml
setup.py

**Checks**
This PR closes #353

release_v4.0.2

---

Dockerfile
package.xml
setup.py

**Checks**
This PR closes #356

#356 check

---

.github/workflows/release.yml
package.xml
setup.py

change yml

---

necst/core/commander.py
necst/definitions.py
necst/executors/analog_logger.py
necst/rx/__init__.py
necst/rx/analog_logger.py

**Checks**
This PR closes #343

#343 analog

---

necst/rx/attenuator.py

#379 Fix attenuator

---

necst/core/commander.py
necst/ctrl/calibrator/chopper.py
necst/procedures/measurement/knife_edge.py

#382 knife edge

---

bin/knife_edge.py
necst/core/commander.py
necst/procedures/measurement/__init__.py
necst/procedures/measurement/knife_edge.py

"#382 actual device test passed"
